<a href="https://colab.research.google.com/github/AngelinaSmi/Digital-image-processing/blob/main/Lb1_DIP_Smirnova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторная работа № 1 Смирновой А.Е. 24ВВИм1**

Задание: Необходимо средствами библиотеки numpy сгенерировать матрицу со случайными значениями и привести все значения в диапазон от 0 до 255

Установим библиотеку NumPy

In [1]:
!pip3 install numpy

Подключим библиотеку

In [2]:
import numpy as np

Создадим матрицу со случайными значениями

In [10]:
rnd = np.random.randint(1000, size=(7, 10))
print(rnd)

[[815  80 396 583 924 313 347 822 797 500]
 [114 469 884 552  92  27 646 373 490 412]
 [315 574 796 128 684 895 738 779 345 217]
 [691 229 130 287 626 533  22 502 453 840]
 [809  84   0 789 656 984  74  12 871 140]
 [824 710 250 744 458 461 828 735 739 163]
 [264 122 674 477 844 455 599   5 194 198]]


Приведем все занчения в диапазон от 0 до 255. Находим минимальное и макисмальное значения матрицы и преобразуем их в 0 и 255.

In [11]:
mn, mx = rnd.min(), rnd.max()
rnd_new = ((rnd - mn) / (mx - mn) * 255).clip(0,255).astype(np.uint8)
print(rnd_new)

[[211  20 102 151 239  81  89 213 206 129]
 [ 29 121 229 143  23   6 167  96 126 106]
 [ 81 148 206  33 177 231 191 201  89  56]
 [179  59  33  74 162 138   5 130 117 217]
 [209  21   0 204 170 255  19   3 225  36]
 [213 183  64 192 118 119 214 190 191  42]
 [ 68  31 174 123 218 117 155   1  50  51]]
